# Site settings
title: Shashwat's Blog
email: bhatt.shaswat@gmail.com
description: "Personal blog about programming, learning, open-source, startups, git, linux, etc."
baseurl: ""
url: "https://shashwatbhatt.github.io"
twitter_username: BhattShashwat
github_username:  shashwatbhatt

# Build settings
markdown: kramdown
permalink: pretty
excerpt_separator: "<!-- more -->"

gems:
  - jekyll-sitemap

